fix: remove Elixir from module_name_prefix
ash-project/igniter pull request #37
Opened 2024-07-07 21:30 UTC by ibarakaiev

### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

I do not know why, but the original implementation in some cases prepends `Elixir` to the return value in `Igniter.Code.Module.module_name_prefix/0`, whereas in some cases it doesn't. However, the new implementation empirically never prepends it.

2024-07-07 21:40 UTC, ibarakaiev commented
This example is showcased in the generated `DataCase` here: https://github.com/ash-project/ash_postgres/pull/344. With the modification in this PR, `Elixir.` no longer appears in module name. Again, not sure why :)

2024-07-08 19:11 UTC, zachdaniel commented on lib/igniter/code/module.ex
> +    Mix.Project.get!() |> Module.split() |> List.first() |> String.to_atom()
This isn't quite right, because if the mix project is something like `Foo.Bar.MixProject` then the prefix should be `Foo.Bar`.

2024-07-08 19:12 UTC, zachdaniel requested changes
I'm not sure why `Elixir.` is being added as a prefix, but the logic of taking only the first part of the module name will produce incorrect results in certain mix projects as described.

2024-07-10 12:39 UTC, zachdaniel commented
I see what's happening here :) When you string interpolate a module, i.e `"#{module}"` it always adds the `Elixir` prefix. For this reason, we do `"#{inspect(module)}"`.

2024-07-10 12:39 UTC, closed without merging